apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "order-ondemand"
  namespace: spark-team-a
  labels:
    app: "order-ondemand"
    queue: root.test 
spec:
  type: Python
  sparkVersion: "4.0.1"
  pythonVersion: "3"
  mode: cluster
  image: "spark:4.0.1-scala2.13-java17-python3-r-ubuntu"
  imagePullPolicy: IfNotPresent
  mainApplicationFile: "s3a://$S3_BUCKET/scripts/pyspark-order.py"
  arguments:
    - "s3a://$S3_BUCKET/order/input/"
    - "s3a://$S3_BUCKET/order/output/ondemand/"
  sparkConf:
    # S3 access with IRSA Role and tuning
    "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "spark.hadoop.fs.s3a.aws.credentials.provider": "software.amazon.awssdk.auth.credentials.WebIdentityTokenFileCredentialsProvider"
    "spark.hadoop.fs.s3a.connection.timeout": "1200000"
    "spark.hadoop.fs.s3a.path.style.access": "true"
    "spark.hadoop.fs.s3a.connection.maximum": "200"
    "spark.hadoop.fs.s3a.fast.upload": "true"
    "spark.hadoop.fs.s3a.readahead.range": "256K"
    "spark.hadoop.fs.s3a.input.fadvise": "random"
    # K8s Pod naming
    "spark.app.name": "order-ondemand"
    "spark.kubernetes.driver.pod.name": "order-ondemand-driver"
    "spark.kubernetes.executor.podNamePrefix": "order-ondemand-executor"
    # Spark Event logs
    "spark.eventLog.enabled": "true"
    "spark.eventLog.dir": "s3a://$S3_BUCKET/spark-event-logs"
    "spark.eventLog.rolling.enabled": "true"
    "spark.eventLog.rolling.maxFileSize": "64m"
    # Expose Spark metrics for Prometheus
    "spark.ui.prometheus.enabled": "true"
    "spark.executor.processTreeMetrics.enabled": "true"
    "spark.metrics.conf.*.sink.prometheusServlet.class": "org.apache.spark.metrics.sink.PrometheusServlet"
    "spark.metrics.conf.driver.sink.prometheusServlet.path": "/metrics/driver/prometheus/"
    "spark.metrics.conf.executor.sink.prometheusServlet.path": "/metrics/executors/prometheus/"
    "spark.metrics.conf.shuffleService.sink.prometheusServlet.path": "/metrics/shuffle/prometheus/"
    "spark.metrics.conf.master.sink.prometheusServlet.path": "/metrics/master/prometheus/"
    "spark.metrics.conf.applications.sink.prometheusServlet.path": "/metrics/applications/prometheus/"
    # If your prometheus is configured to setup scrape jobs from annotations.
    #   you can use these options to configure the scrape job.
    # "spark.kubernetes.driver.annotation.prometheus.io/scrape": "true"
    # "spark.kubernetes.driver.annotation.prometheus.io/path": "/metrics/executors/prometheus/"
    # "spark.kubernetes.driver.annotation.prometheus.io/port": "4040"
    # "spark.kubernetes.driver.service.annotation.prometheus.io/scrape": "true"
    # "spark.kubernetes.driver.service.annotation.prometheus.io/path": "/metrics/driver/prometheus/"
    # "spark.kubernetes.driver.service.annotation.prometheus.io/port": "4040"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 3
    onSubmissionFailureRetryInterval: 20
  driver:
    podSecurityContext:
      fsGroup: 185
    cores: 2
    coreLimit: "4200m"
    memory: "4g"
    memoryOverhead: "2g"
    serviceAccount:  spark-team-a
    # labels:
    #   sparkVersion: "4.0.1"
    nodeSelector:
      NodeGroupType: "SparkComputeOnDemand"
  executor:
    podSecurityContext:
      fsGroup: 185
    cores: 2
    coreLimit: "2000m"
    instances: 4
    memory: "4g"
    memoryOverhead: "2g"
    serviceAccount:  spark-team-a
    # labels:
    #   sparkVersion: "4.0.1"
    nodeSelector:
      NodeGroupType: "SparkComputeOnDemand"
