global:
  datahub:
    version: v1.2.0
  
  elasticsearch:
    host: "opensearch-cluster-master"
    port: "9200"
    
  kafka:
    bootstrap:
      server: "cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
  sql:
    datasource:
      host: "datahub-prerequisites-postgresql:5432"
      hostForpostgresqlClient: "datahub-prerequisites-postgresql"
      port: "5432"
      url: "jdbc:postgresql://datahub-prerequisites-postgresql:5432/datahub"
      driver: "org.postgresql.Driver"
      username: "postgres"
      password:
        secretRef: postgresql-secrets
        secretKey: postgres-password

datahub-gms:
  serviceAccount:
    create: true
    name: datahub-sa
  service:
    type: ClusterIP

datahub-frontend:
  enabled: true
  service:
    extraLabels: {}
    type: ClusterIP

datahub-mae-consumer:
  enabled: true

datahub-mce-consumer:
  enabled: true

# Use OpenSearch from prerequisites
elasticsearchSetupJob:
  enabled: true
  extraEnvs:
    - name: USE_AWS_ELASTICSEARCH
      value: "true"

postgresqlSetupJob:
  enabled: true

mysqlSetupJob:
  enabled: false

kafkaSetupJob:
  resources:
    limits:
      cpu: 5000m

datahubSystemUpdate:
  esources:
    limits:
      cpu: 5000m

# Disable embedded services
elasticsearch:
  enabled: false

postgresql:
  enabled: false

redis:
  enabled: false

mysql:
  enabled: false
