apiVersion: v1
data:
  escape.lua: |
    function escape_json(tag, timestamp, record)
        if record.log then
            record.log = string.gsub(record.log, "\n", " ")
            record.log = string.gsub(record.log, "\r", " ")
            record.log = string.gsub(record.log, "\t", " ")
            record.log = string.gsub(record.log, '"', '\\"')
        end
        
        if record.message then
            record.message = string.gsub(record.message, "\n", " ")
            record.message = string.gsub(record.message, "\r", " ")
            record.message = string.gsub(record.message, "\t", " ")
            record.message = string.gsub(record.message, '"', '\\"')
        end
        
        return 1, timestamp, record
    end

kind: ConfigMap
metadata:
  name: lua-scripts
  namespace: kube-system
