apiVersion: v1
kind: Pod
metadata:
  name: event-producer
  namespace: workshop
spec:
  terminationGracePeriodSeconds: 10
  containers:
  - name: event-producer-container
    image: docker.io/library/ubuntu:24.04
    command: ["/bin/sh", "-c"]
    args: ["sleep 172800"]
