apiVersion: v1
kind: Pod
metadata:
  name: kafka-debug
  namespace: workshop
spec:
  containers:
  - name: kafka-consumer
    image: confluentinc/cp-kafka:8.0.1
    command: ["kafka-console-consumer"]
    args:
      - "--bootstrap-server=cluster-broker-0.cluster-kafka-brokers.kafka.svc:9092"
      - "--topic=visitor-checkins"
      - "--from-beginning"
  restartPolicy: Never
