
prometheus:
  prometheusSpec:
    # Increase Resources requested by the Prometheus Pod
    resources:
      requests:
        cpu: "2"
        memory: 1Gi
    retention: 15d
    scrapeInterval: 30s
    evaluationInterval: 30s
    scrapeTimeout: 10s
    # bump storage time locally for metrics
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          storageClassName: gp3
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Gi
    # Scrape Cost metrics for Karpenter and Yunikorn add-ons
    additionalScrapeConfigs:
      - job_name: yunikorn
        honor_labels: true
        scrape_interval: 15s
        scrape_timeout: 10s
        metrics_path: /ws/v1//metrics
        scheme: http
        dns_sd_configs:
          - names:
              - yunikorn-service.yunikorn.svc
            type: 'A'
            port: 9080
      - job_name: karpenter
        kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - karpenter
        relabel_configs:
        - source_labels: [__meta_kubernetes_endpoint_port_name]
          regex: http-metrics
          action: keep

alertmanager:
  enabled: false

# Disable scrapers that aren't functional in AWS
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false

kube-state-metrics:
  resources:
    requests:
      cpu: "2"
      memory: 1Gi

grafana:
  enabled: true
  defaultDashboardsEnabled: true
  resources:
   requests:
     cpu: "2"
     memory: 1Gi