apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yunikorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://apache.github.io/yunikorn-release
    chart: yunikorn
    targetRevision: "1.7.0"
    helm:
      valuesObject:
        ${values}

  destination:
    server: https://kubernetes.default.svc
    namespace: yunikorn-system

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
