{
 "title": "Spark-K8s-Operator-Scale-Test-Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Spark-operator Pod Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Max CPU Usage (vCPU)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(sum by(namespace, pod, container) (irate(container_cpu_usage_seconds_total{image!=\"\", namespace=\"spark-operator\"}[5m])) * on(namespace, pod) group_left(node) topk by(namespace, pod) (1, max by(namespace, pod, node) (kube_pod_info{node!=\"\"}))) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Memory Usage (in GB)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\", namespace=\"spark-operator\"}) by (pod) / 1e9",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Receive Bytes (in MiB)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"spark-operator\"}[5m])) by (pod) / 1e7",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Spark Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Start Latency Percentiles (in sec)",
   "type": "timeseries",
   "description": "Start Latency Percentiles",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(spark_application_start_latency_seconds_histogram_bucket{container=\"spark-operator-controller\"}[5m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(spark_application_start_latency_seconds_histogram_bucket{container=\"spark-operator-controller\"}[5m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(spark_application_start_latency_seconds_histogram_bucket{container=\"spark-operator-controller\"}[5m])) by (le))",
     "legendFormat": "P50"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Spark Jobs Count",
   "type": "gauge",
   "description": "Spark Jobs (Submitted and Running)",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "spark_application_count", "legendFormat": "Total Spark Jobs Created" },
    {
     "expr": "spark_application_failure_count",
     "legendFormat": "Total Failed Spark Jobs"
    },
    {
     "expr": "spark_application_success_count",
     "legendFormat": "Total Succesful Spark Jobs"
    },
    {
     "expr": "spark_application_running_count",
     "legendFormat": "Spark Jobs Running"
    },
    {
     "expr": "sum(increase(spark_application_submit_count[1m]))",
     "legendFormat": "Total Number of Submitted Jobs in last 1 minute"
    }
   ]
  },
  {
   "title": "Spark Executor Health",
   "type": "piechart",
   "description": "Spark Executor Health",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_executor_success_count)",
     "legendFormat": "Executors Running Count"
    },
    {
     "expr": "sum(spark_executor_failure_count)",
     "legendFormat": "Executor Failure Count"
    }
   ]
  },
  {
   "title": "Job Success Rate ",
   "type": "timeseries",
   "description": "Spark Job Success Rate Percentage",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "(sum(rate(spark_application_success_count[5m]))) / (sum(rate(spark_application_submit_count[5m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Failure Rate ",
   "type": "barchart",
   "description": "Spark Job Failure Rate Percentage",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "(sum(rate(spark_application_failure_count[5m]))) / (sum(rate(spark_application_submit_count[5m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Failure Trend",
   "type": "timeseries",
   "description": "Job Failure Trend",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(spark_application_failure_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Kubernetes Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "P90 API server latency for all request types",
   "type": "timeseries",
   "description": "P90 API server latency for all request types",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\"}[5m])) by (le, instance)) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Server Request Duration (sec)",
   "type": "timeseries",
   "description": "API Server Request Duration by Verb (seconds)",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, max(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\"}[5m])) by (le, verb)) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Admission Webhook Admission Duration (sec)",
   "type": "timeseries",
   "description": "Admission Webhook Admission Duration Seconds bucket",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_admission_webhook_admission_duration_seconds_bucket[5m])) by (le, operation, name)) > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "ETCD P99 Latency(seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_request_duration_seconds_bucket[5m])) \n  by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Server Total DB Size (GiB)",
   "type": "timeseries",
   "description": "API Server Total DB Size (in GiB)",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "max(apiserver_storage_size_bytes{storage_cluster_id=\"etcd-0\"}) / 1e9",
     "legendFormat": "Total Etcd DB Size (GiB)"
    }
   ]
  },
  {
   "title": "Spark Application Object Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "max(apiserver_storage_objects{resource=\"sparkapplications.sparkoperator.k8s.io\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spark Application Object Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "max(apiserver_storage_objects{resource=\"nodes\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Object Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "expr": "max(apiserver_storage_objects{resource=\"pods\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "WorkQueue Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Work Duration P Latency",
   "type": "timeseries",
   "description": "Work Duration P99 and P95 Latency",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_work_duration_seconds_bucket{container=\"spark-operator-controller\"}[5m])) by (verb, scope,le)) > 0",
     "legendFormat": "P99 Latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(workqueue_work_duration_seconds_bucket{container=\"spark-operator-controller\"}[5m])) by (verb, scope,le)) > 0",
     "legendFormat": "P95 Latency"
    }
   ]
  },
  {
   "title": "Queue Duration P Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 40 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"spark-operator/spark-operator-podmonitor\"}[5m])) by (verb, scope, le)) > 0",
     "legendFormat": "P99 Latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"spark-operator/spark-operator-podmonitor\"}[5m])) by (le)) > 0",
     "legendFormat": "P95 Latency"
    }
   ]
  },
  {
   "title": "Unfinished Work",
   "type": "timeseries",
   "description": "Unfinished Work in Seconds",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(workqueue_unfinished_work_seconds{container=\"spark-operator-controller\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Longest Running Controller Thread",
   "type": "timeseries",
   "description": "Longest Running Controller Thread",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "max(workqueue_longest_running_processor_seconds{container=\"spark-operator-controller\"})/1e6",
     "legendFormat": "Longest Running Controller Thread"
    }
   ]
  },
  {
   "title": "Work Queue Total Adds",
   "type": "barchart",
   "description": "Total number of adds handled by workqueue",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 45 },
   "targets": [
    {
     "expr": "rate(workqueue_adds_total{container=\"spark-operator-controller\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Work Queue Total Retries",
   "type": "barchart",
   "description": "Work Queue Total Retries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 45 },
   "targets": [
    {
     "expr": "sum(rate(workqueue_retries_total{container=\"spark-operator-controller\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Work Queue Depth",
   "type": "timeseries",
   "description": "Work Queue Depth",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 50 },
   "targets": [
    { "expr": "sum(rate(workqueue_depth[5m]))", "legendFormat": "__auto" }
   ]
  }
 ]
}